from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = true

pre_bump_hooks = [
  "echo {{version}}",
]

post_bump_hooks = [
  "git push",
  "git push origin {{version}}",
]

pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = [
  { username = "atlasoft", signature = "Juan Pablo Cisneros"}
]

[bump_profiles]

[packages]
