name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Semver release
      uses: cocogitto/cocogitto-action@main
      with:
        release: true
        git-user: 'Cog Bot'
        git-user-email: 'mycoolproject@org.org'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
